---
- name: Ensure Required Items
  fail:
    msg: "Please ensure '{{ item.use }}' is set"
  run_once: true
  when:
    - item.file is undefined or item.file | length == 0
  with_items:
    - { file: _keyfile, use: "New Key File" }
    - { file: keys_base, use: "Path to base folder for keys" }
    - { file: keygen, use: "Key Generation Configuration Object" }
  tags: ["always"]

- name: Set the comment for the key
  set_fact:
    comment: "{{ fqdn }}"
  when: comment is undefined or comment | length == 0
  tags: ["always"]

- name: Set _keypath
  set_fact:
    _keypath: "{{ keys_base }}/{{ _keyfile }}"
  tags: ["always"]

- name: Set the keypath derivatives
  set_fact:
    _keypath_pub: "{{ _keypath }}.pub"
    _keypath_pem: "{{ _keypath }}.pem"
    _keypath_ppk: "{{ _keypath }}.ppk"
  tags: ["always"]

- include_tasks: clear.yml
  tags:
    - regenerate

- include_tasks: create.yml
  tags:
    - create
    - regenerate

- include_tasks: add.yml
  tags:
    - add

- include_tasks: remove.yml
  tags:
    - remove
